### ISSUE TITLE
sauce.version

### ISSUE THREAD

**Issue by JBallin** [screener-io/screener-runner#101]
Currently we can update sauce by setting the `SAUCE_CONNECT_VERSION` environment variable, but I think it would be simpler to set this as part of the `sauce` screener config (while maintaining the env var to be non-breaking or an override of the config).

#### Relevant line:
https://github.com/screener-io/screener-runner/blob/c02f9e43c7399d1b6f33e478bedffd81804cd904/src/tunnel.js#L17

#### Suggested change:

```js
scVersion: process.env.SAUCE_CONNECT_VERSION || sauce.version || '4.6.2', 
```

------

Additionally, I think that the ability to set the sauce version should be documented in the README and/or the default version should be updated (4.6.2 was unsupported as of 3/31/21).

**Comment by loyalchow** [comment]
@JBallin sorry for the late reply - a PR has been started for this here: https://github.com/screener-io/screener-runner/pull/103
