### ISSUE TITLE
Screener doesn't handle dynamically loading elements in a screenshot

### ISSUE THREAD

**Issue by nadvolod** [screener-io/screener-runner#73]
Used the runner and it captured my whole web page, but missed a bunch of the dynamically loading elements. Not sure if you have access to this:
https://screener.io/v2/states/B1VWugL7r.user-my-project-repo/(default)/1024x768/Chrome/ultimate-qa-home-page-0

**Comment by loyalchow** [comment]
@nadvolod Thanks for reaching out. Appears content has not fully loaded and height may potentially be changing as page is scrolled.

Here is a gist that pre-scrolls/loads that hopefully helps:
https://gist.github.com/loyalchow/a9fd013e46ef3f2777310dc683e8e921

**Comment by nadvolod** [comment]
Worked great 👍
