### ISSUE TITLE
Is it possible to run any device on Sauce Labs?

### ISSUE THREAD

**Issue by nadvolod** [screener-io/screener-runner#74]
Hi, I'm going through the docs here and I was able to successfully integrate into Sauce. My question is whether it's possible to run on any browser/os/mobile device in Sauce Labs? I know that Edge and Safari are supported. But can I pick anything else from Sauce and just set it in the config?

**Comment by loyalchow** [comment]
@nadvolod we do not yet support Sauce RDC/EMUSIM, but this is on the roadmap
