### ISSUE TITLE
Replace `sauce-connect-launcher` with SC integration in our own `saucelabs` package.

### ISSUE THREAD

**Issue by christian-bromann** [screener-io/screener-runner#95]
With [`v4.4.0`](https://github.com/saucelabs/node-saucelabs/releases/tag/v4.1.0) of our `saucelabs` NPM package we support starting/stopping of SC tunnels. I recommend to switch to this version.

**Comment by loyalchow** [comment]
@christian-bromann created a ticket for this

**Comment by loyalchow** [comment]
Added: https://github.com/screener-io/screener-runner/pull/97
